org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true
ksp.useKSP2=true
kapt.use.worker.api=false
dagger.hilt.android.gradle.disableCrossCompilationRootValidation=true
